# Generated by Django 3.1.7 on 2021-12-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=100000)),
                ('publishedAt', models.DateTimeField()),
                ('video_id', models.CharField(max_length=1000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=1000)),
            ],
        ),
    ]
